package com.jp.eslocapi.api.entities;

public enum EnumType {
	AGRICULTOR_FAMILIAR, 
	DEMAIS_PRODUTORES, 
	TECNICO_EMATER, 
	TECNICO_PREFEITURA,
	TECNICO_SINDICATO,
	TECNICO_OUTROS, 
	FUNC_CEDIDO,
	
}
